server:
  port: 8088

# spring:
#   datasource:
#     url: jdbc:mysql://w7yeb6bhb9sv8mr4:spckwr2h13ehecsl@wb39lt71kvkgdmw0.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/gauzrat9dewkb40z?reconnect=true&characterEncoding=UTF-8
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     username: w7yeb6bhb9sv8mr4
#     password: spckwr2h13ehecsl

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql8-container:3307/ShopApp?serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Abc123456789@}

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/twinkle?reconnect=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:

  spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: redis-container # Default to 'localhost' if not provided
    port: ${REDIS_HOST:6379}   # Default to 6379 if not provided
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en




api:
  prefix: api/v1

jwt:
  expiration: 2592000
    #30 days = 30 * 24 * 60 * 60
  secretKey: XsxIrJU5YktIqIJDJr7sYUrUYx+joroTKsMAwjqigm8=


